drop table pavilon cascade constraints;
drop table pozice cascade constraints;
drop table zivocisny_druh cascade constraints;
drop table jedinec cascade constraints;
drop table mereni cascade constraints;


create table pavilon (
    id varchar(10) primary key,
    druh varchar(40)
);

create table pozice (
    id varchar(20) primary key,
    prostredi varchar(30),
    datum_udrzby date,
    typ varchar(30),
    --
    -- specification | vybeh:
    plocha numeric(7, 2) default null,
    --
    -- specification | klec:
    objem numeric(7, 2) default null,
    pavilon varchar(10) default null,
    foreign key (pavilon)
        references pavilon (id)
        on delete cascade
);

create table zivocisny_druh (
    nazev varchar(100) primary key,
    charakteristika varchar(1024)
);

create table jedinec (
    id varchar(20) primary key,
    jmeno varchar(30),
    datum_narozeni date not null,
    datum_umrti date default null,
    zastupce_druhu varchar(30) not null,
    foreign key (zastupce_druhu)
        references zivocisny_druh (nazev)
        on delete cascade, -- on update cascade
    pozice varchar(20) default null, -- animal 'jedinec' is on position 'pozice'
    foreign key (pozice)
        references pozice (id)
);

create table mereni (
  id number(5) generated by default on null as identity primary key,
  id_jedince number(10) not null
      references jedinec (id)
      on delete cascade,
  datum_mereni date,
  zdravotni_stav varchar(1024),
  hmotnost numeric(7, 2),
  vyska numeric(7, 2)
);
